# Generated by Django 4.1 on 2022-09-02 20:50

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "animal_type",
                    models.CharField(
                        choices=[("DOG", "Dog"), ("CAT", "Cat")],
                        default="DOG",
                        max_length=3,
                    ),
                ),
                (
                    "petfinder_id",
                    models.CharField(
                        blank=True, default=None, max_length=32, null=True, unique=True
                    ),
                ),
                ("is_mixed_breed", models.BooleanField()),
                ("is_unknown_breed", models.BooleanField()),
                (
                    "sex",
                    models.CharField(
                        choices=[("F", "Female"), ("M", "Male")], max_length=1
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("XS", "X-Small"),
                            ("S", "Small"),
                            ("M", "Medium"),
                            ("L", "Large"),
                            ("XL", "X-Large"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "age",
                    models.CharField(
                        choices=[
                            ("BABY", "Puppy/Kitten"),
                            ("YOUNG", "Young"),
                            ("ADULT", "Adult"),
                            ("SENIOR", "Senior"),
                        ],
                        max_length=8,
                    ),
                ),
                ("is_spayed_neutered", models.BooleanField()),
                ("is_vaccinations_current", models.BooleanField()),
                ("is_house_trained", models.BooleanField()),
                ("special_needs", models.TextField(blank=True)),
                ("vaccinations_notes", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                (
                    "behaviour_dogs",
                    models.CharField(
                        choices=[
                            ("POOR", "Poor"),
                            ("SELECTIVE", "Selective"),
                            ("GOOD", "Good"),
                            ("NOT_TESTED", "Not tested"),
                        ],
                        default="NOT_TESTED",
                        max_length=10,
                    ),
                ),
                (
                    "behaviour_cats",
                    models.CharField(
                        choices=[
                            ("POOR", "Poor"),
                            ("SELECTIVE", "Selective"),
                            ("GOOD", "Good"),
                            ("NOT_TESTED", "Not tested"),
                        ],
                        default="NOT_TESTED",
                        max_length=10,
                    ),
                ),
                (
                    "behaviour_kids",
                    models.CharField(
                        choices=[
                            ("POOR", "Poor"),
                            ("SELECTIVE", "Selective"),
                            ("GOOD", "Good"),
                            ("NOT_TESTED", "Not tested"),
                        ],
                        default="NOT_TESTED",
                        max_length=10,
                    ),
                ),
                ("is_euth_listed", models.BooleanField()),
                ("euth_date", models.DateField(blank=True, default=None, null=True)),
                ("primary_photo", models.ImageField(blank=True, upload_to="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Awg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "petfinder_id",
                    models.CharField(
                        blank=True, default=None, max_length=32, null=True
                    ),
                ),
                (
                    "geo_location",
                    django.contrib.gis.db.models.fields.PointField(srid=4326),
                ),
                (
                    "zip_code",
                    models.CharField(
                        blank=True, default=None, max_length=16, null=True
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, default=None, max_length=32, null=True
                    ),
                ),
                ("state", models.CharField(max_length=2)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Breed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                (
                    "animal_type",
                    models.CharField(
                        choices=[("DOG", "Dog"), ("CAT", "Cat")],
                        default="DOG",
                        max_length=3,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ZipCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zip_code", models.CharField(max_length=16, unique=True)),
                (
                    "geo_location",
                    django.contrib.gis.db.models.fields.PointField(srid=4326),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnimalImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("primary_photo", models.ImageField(upload_to="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="caim_base.animal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnimalComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField()),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="caim_base.animal",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="animal",
            name="awg",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="caim_base.awg"
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="primary_breed",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="primary_animal_set",
                to="caim_base.breed",
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="secondary_breed",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="secondary_animal_set",
                to="caim_base.breed",
            ),
        ),
        migrations.CreateModel(
            name="AnimalShortList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="caim_base.animal",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("animal", "user")},
            },
        ),
    ]
