# Generated by Django 4.1 on 2022-09-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caim_base", "0004_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="awg",
            name="awg_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CENTER_ONLY", "Center only"),
                    ("FOSTER_ONLY", "Foster only"),
                    ("CENTER_AND_FOSTER", "Both"),
                ],
                default=None,
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="awg",
            name="company_ein",
            field=models.CharField(blank=True, default=None, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="awg",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="awg",
            name="email",
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="awg",
            name="facebook_url",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="awg",
            name="has_501c3_tax_exemption",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="awg",
            name="instagram_url",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="awg",
            name="phone",
            field=models.CharField(blank=True, default=None, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="awg",
            name="tiktok_url",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="awg",
            name="twitter_url",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="awg",
            name="website_url",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="awg",
            name="workwith_cats",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="awg",
            name="workwith_dogs",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="awg",
            name="workwith_other",
            field=models.BooleanField(default=False),
        ),
    ]
