# Generated by Django 4.1 on 2022-09-14 09:33

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("caim_base", "0005_awg_awg_type_awg_company_ein_awg_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="awg",
            name="email",
            field=models.EmailField(blank=True, default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="awg",
            name="facebook_url",
            field=models.URLField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="awg",
            name="instagram_url",
            field=models.URLField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="awg",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, default=None, max_length=128, null=True, region=None
            ),
        ),
        migrations.AlterField(
            model_name="awg",
            name="tiktok_url",
            field=models.URLField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="awg",
            name="twitter_url",
            field=models.URLField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="awg",
            name="website_url",
            field=models.URLField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
