# Generated by Django 4.1 on 2022-09-15 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("caim_base", "0006_alter_awg_email_alter_awg_facebook_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AwgMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("canEditProfile", models.BooleanField(default=False)),
                ("canManageAnimals", models.BooleanField(default=False)),
                ("canManageMembers", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "awg",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="caim_base.awg"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
