# Generated by Django 4.1 on 2022-09-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("caim_base", "0008_alter_awgmember_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="awg",
            name="awg_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SHELTER_ONLY", "Shelter only"),
                    ("FOSTER_ONLY", "Foster only"),
                    ("SHELTER_AND_FOSTER", "Both"),
                ],
                default=None,
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="awg",
            name="company_ein",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=16,
                null=True,
                verbose_name="Employer Identification Number (EIN)",
            ),
        ),
        migrations.AlterField(
            model_name="awg",
            name="has_501c3_tax_exemption",
            field=models.BooleanField(
                default=False, verbose_name="501c3 tax exempt charity"
            ),
        ),
        migrations.AlterField(
            model_name="awg",
            name="workwith_cats",
            field=models.BooleanField(default=False, verbose_name="Works with cats?"),
        ),
        migrations.AlterField(
            model_name="awg",
            name="workwith_dogs",
            field=models.BooleanField(default=False, verbose_name="Works with dogs?"),
        ),
        migrations.AlterField(
            model_name="awg",
            name="workwith_other",
            field=models.BooleanField(
                default=False, verbose_name="Works with other animals?"
            ),
        ),
    ]
