# Generated by Django 4.1 on 2022-09-16 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("caim_base", "0009_alter_awg_awg_type_alter_awg_company_ein_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="animal",
            name="is_house_trained",
        ),
        migrations.AddField(
            model_name="animal",
            name="awg_internal_id",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=64,
                null=True,
                verbose_name="AWG internal ID",
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="awg_profile_url",
            field=models.URLField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="AWG animal profile URL",
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="animal",
            name="is_special_needs",
            field=models.BooleanField(default=False, verbose_name="Has special needs"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="animal",
            name="awg",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="caim_base.awg",
                verbose_name="AWG",
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="behaviour_cats",
            field=models.CharField(
                choices=[
                    ("POOR", "Poor"),
                    ("SELECTIVE", "Selective"),
                    ("GOOD", "Good"),
                    ("NOT_TESTED", "Not tested"),
                ],
                default="NOT_TESTED",
                max_length=10,
                verbose_name="Behavour with cats",
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="behaviour_dogs",
            field=models.CharField(
                choices=[
                    ("POOR", "Poor"),
                    ("SELECTIVE", "Selective"),
                    ("GOOD", "Good"),
                    ("NOT_TESTED", "Not tested"),
                ],
                default="NOT_TESTED",
                max_length=10,
                verbose_name="Behavour with dogs",
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="behaviour_kids",
            field=models.CharField(
                choices=[
                    ("POOR", "Poor"),
                    ("SELECTIVE", "Selective"),
                    ("GOOD", "Good"),
                    ("NOT_TESTED", "Not tested"),
                ],
                default="NOT_TESTED",
                max_length=10,
                verbose_name="Behavour with kidw",
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="euth_date",
            field=models.DateField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Scheduled euthanasia date",
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="is_euth_listed",
            field=models.BooleanField(verbose_name="Is scheduled for euthanasia"),
        ),
        migrations.AlterField(
            model_name="animal",
            name="is_spayed_neutered",
            field=models.BooleanField(verbose_name="Is spayed / neutered"),
        ),
        migrations.AlterField(
            model_name="animal",
            name="is_vaccinations_current",
            field=models.BooleanField(verbose_name="Vaccinations are up to date"),
        ),
        migrations.AlterField(
            model_name="animal",
            name="special_needs",
            field=models.TextField(blank=True, verbose_name="Special needs details"),
        ),
        migrations.AlterField(
            model_name="animal",
            name="vaccinations_notes",
            field=models.TextField(blank=True, verbose_name="Vaccination notes"),
        ),
        migrations.AlterField(
            model_name="awg",
            name="awg_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SHELTER_ONLY", "Shelter only"),
                    ("FOSTER_ONLY", "Foster only"),
                    ("SHELTER_AND_FOSTER", "Both"),
                ],
                default=None,
                max_length=32,
                null=True,
                verbose_name="AWS type",
            ),
        ),
        migrations.AlterField(
            model_name="awg",
            name="facebook_url",
            field=models.URLField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="Facebook URL",
            ),
        ),
        migrations.AlterField(
            model_name="awg",
            name="instagram_url",
            field=models.URLField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="Instagram URL",
            ),
        ),
        migrations.AlterField(
            model_name="awg",
            name="tiktok_url",
            field=models.URLField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="TikTok URL",
            ),
        ),
        migrations.AlterField(
            model_name="awg",
            name="twitter_url",
            field=models.URLField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="Twitter URL",
            ),
        ),
        migrations.AlterField(
            model_name="awg",
            name="website_url",
            field=models.URLField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="Website URL",
            ),
        ),
    ]
