# Generated by Django 4.1 on 2022-09-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("caim_base", "0010_remove_animal_is_house_trained_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="awg",
            name="is_exact_location_shown",
            field=models.BooleanField(
                default=False, verbose_name="Show exact location?"
            ),
        ),
    ]
