# Generated by Django 4.1 on 2022-09-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("caim_base", "0013_alter_awg_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="awg",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="Is listed on site?"),
        ),
        migrations.AlterField(
            model_name="awg",
            name="awg_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SHELTER_ONLY", "Shelter only"),
                    ("FOSTER_ONLY", "Foster only"),
                    ("SHELTER_AND_FOSTER", "Both Shelter and Foster"),
                ],
                default=None,
                max_length=32,
                null=True,
                verbose_name="Organisation type",
            ),
        ),
    ]
