# Generated by Django 4.1 on 2022-09-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("caim_base", "0015_alter_awg_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="awg",
            name="status",
            field=models.CharField(
                choices=[
                    ("APPLIED", "Applied"),
                    ("PUBLISHED", "Published"),
                    ("UNPUBLISHED", "Unpublished"),
                ],
                default="APPLIED",
                max_length=16,
                verbose_name="Listing status",
            ),
        ),
        migrations.AlterField(
            model_name="awg",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Organization name"),
        ),
    ]
