# Generated by Django 4.1 on 2022-09-20 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("caim_base", "0016_awg_status_alter_awg_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="awg",
            name="is_published",
        ),
    ]
