# Generated by Django 4.1 on 2022-10-23 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("caim_base", "0021_savedsearch_is_notifications_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedsearch",
            name="check_every_seconds",
            field=models.DurationField(default=datetime.timedelta(days=1)),
        ),
        migrations.AddField(
            model_name="savedsearch",
            name="last_checked_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
