# Generated by Django 4.1 on 2022-10-23 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("caim_base", "0022_savedsearch_check_every_seconds_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="savedsearch",
            old_name="check_every_seconds",
            new_name="check_every",
        ),
    ]
