# Generated by Django 4.1 on 2022-11-02 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("caim_base", "0022_animalsubcomment"),
        ("caim_base", "0023_rename_check_every_seconds_savedsearch_check_every"),
    ]

    operations = []
