# Generated by Django 4.1 on 2023-02-20 11:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("caim_base", "0026_fostererprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fostererprofile",
            name="description",
        ),
        migrations.AddField(
            model_name="fostererprofile",
            name="category_of_animals",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("ADULT_FEMALE", "Adult female"),
                        ("ADULT_MALE", "Adult male"),
                        ("PREGNANT_MOTHER", "Pregnant mom"),
                        ("MOTHER_WITH_BABIES", "Mom with nursing babies"),
                        ("BABIES", "Puppies / kittens"),
                        ("PIT_BULLY_BREEDS", "Pit and/or Bully breeds"),
                    ],
                    max_length=32,
                ),
                blank=True,
                default=None,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="fostererprofile",
            name="type_of_animals",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[("DOGS", "Dogs"), ("CATS", "Cats")], max_length=32
                ),
                blank=True,
                default=None,
                null=True,
                size=None,
            ),
        ),
    ]
