# Generated by Django 4.1 on 2023-02-20 13:22

import caim_base.models.fosterer
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caim_base", "0027_remove_fostererprofile_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fostererprofile",
            name="agree_share_details",
            field=models.CharField(
                blank=True,
                choices=[("YES", "Yes"), ("NO", "No")],
                default=None,
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="fostererprofile",
            name="behavioural_attributes",
            field=caim_base.models.fosterer.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("GOOD_WITH_DOGS", "Good with dogs"),
                        ("GOOD_WITH_CATS", "Good with cats"),
                        ("GOOD_WITH_KIDS", "Good with children"),
                        ("NO_MEDICAL_ISSUES", "No medical issues"),
                        ("NO_SPECIAL_NEEDS", "No special needs"),
                        ("NO_BEHAVIOURAL_NEEDS", "No behavioral issues"),
                    ],
                    max_length=32,
                ),
                blank=True,
                default=None,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="fostererprofile",
            name="ever_been_convicted_abuse",
            field=models.CharField(
                blank=True,
                choices=[("YES", "Yes"), ("NO", "No")],
                default=None,
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="fostererprofile",
            name="existing_pets_details",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="fostererprofile",
            name="experience_categories",
            field=caim_base.models.fosterer.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("YES", "House / potty training"),
                        ("CRATE", "Crate training"),
                        ("LEASH_WALKING", "Challenges with leash / walking"),
                        ("JUMPING", "Jumping"),
                        ("HIGH_ENERGY", "High energy"),
                        ("OBEDIENCE", "Basic obedience"),
                        ("PUPPIES", "Training puppies"),
                        ("SEPARATION_ANXIETY", "Separation anxiety"),
                        ("FEARS", "Fears / phobias"),
                        ("REACTIVITY", "Reactivity"),
                        ("FOOD_GUARDING", "Food guarding"),
                        ("MEDICAL_ISSUES", "Medical issues"),
                        ("GERIATRIC", "Geriatric concerns"),
                        ("NONE_OF_ABOVE", "None of the above"),
                    ],
                    max_length=32,
                ),
                blank=True,
                default=None,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="fostererprofile",
            name="experience_description",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="fostererprofile",
            name="experience_given_up_pet",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="fostererprofile",
            name="hours_alone_description",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="fostererprofile",
            name="hours_alone_location",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="fostererprofile",
            name="num_existing_pets",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="fostererprofile",
            name="other_info",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="fostererprofile",
            name="people_at_home",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="fostererprofile",
            name="reference_1",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="fostererprofile",
            name="reference_2",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="fostererprofile",
            name="reference_3",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="fostererprofile",
            name="rent_ok_foster_pets",
            field=models.CharField(
                blank=True,
                choices=[("YES", "Yes"), ("NO", "No")],
                default=None,
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="fostererprofile",
            name="rent_own",
            field=models.CharField(
                blank=True,
                choices=[("RENT", "Rent"), ("OWN", "Own")],
                default=None,
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="fostererprofile",
            name="rent_restrictions",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="fostererprofile",
            name="sleep_location",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="fostererprofile",
            name="timeframe",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MAX_2_WEEKS", "Up to 2 weeks"),
                    ("MAX_3_MONTHS", "Up to 3 months"),
                    ("ANY_DURATION", "Any duration"),
                    ("OTHER", "Other (please specify)"),
                ],
                default=None,
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="fostererprofile",
            name="timeframe_other",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="fostererprofile",
            name="yard_fence_over_5ft",
            field=models.CharField(
                blank=True,
                choices=[("YES", "Yes"), ("NO", "No")],
                default=None,
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="fostererprofile",
            name="yard_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NO_YARD", "No yard"),
                    ("UNFENCED", "Unfenced yard"),
                    ("PARTIALLY_FENCED", "Partially fenced yard"),
                    ("FULLY_FENCED", "Fully fenced yard"),
                ],
                default=None,
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="fostererprofile",
            name="category_of_animals",
            field=caim_base.models.fosterer.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("ADULT_FEMALE", "Adult female"),
                        ("ADULT_MALE", "Adult male"),
                        ("PREGNANT_MOTHER", "Pregnant mom"),
                        ("MOTHER_WITH_BABIES", "Mom with nursing babies"),
                        ("BABIES", "Puppies / kittens"),
                        ("PIT_BULLY_BREEDS", "Pit and/or Bully breeds"),
                    ],
                    max_length=32,
                ),
                blank=True,
                default=None,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="fostererprofile",
            name="type_of_animals",
            field=caim_base.models.fosterer.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[("DOGS", "Dogs"), ("CATS", "Cats")], max_length=32
                ),
                blank=True,
                default=None,
                null=True,
                size=None,
            ),
        ),
    ]
