# Generated by Django 4.1 on 2023-07-14 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("caim_base", "0032_alter_animal_behaviour_cats_and_more"),
        ("caim_base", "0032_userprofile_salesforce_id"),
    ]

    operations = []
