# Generated by Django 4.1 on 2023-06-28 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("caim_base", "0032_alter_animal_awg_alter_fosterapplication_animal_and_more"),
        ("caim_base", "0032_alter_animal_behaviour_cats_and_more"),
    ]

    operations = []
