# Generated by Django 4.1 on 2023-07-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("caim_base", "0032_alter_animal_behaviour_cats_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="salesforce_id",
            field=models.CharField(max_length=32, null=True),
        ),
    ]
