# Generated by Django 4.1 on 2023-07-21 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("caim_base", "0033_merge_20230628_1416"),
        ("caim_base", "0033_userprofile_salesforce_id"),
    ]

    operations = []
