# Generated by Django 4.1 on 2023-07-22 00:06

import caim_base.models.fosterer
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caim_base", "0034_merge_20230721_1751"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fostererprofile",
            name="experience_categories",
            field=caim_base.models.fosterer.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("HOUSE_POTTY", "House / potty training"),
                        ("CRATE", "Crate training"),
                        ("LEASH_WALKING", "Challenges with leash / walking"),
                        ("JUMPING", "Jumping"),
                        ("HIGH_ENERGY", "High energy"),
                        ("OBEDIENCE", "Basic obedience"),
                        ("PUPPIES", "Training puppies"),
                        ("SEPARATION_ANXIETY", "Separation anxiety"),
                        ("FEARS", "Fears / phobias"),
                        ("REACTIVITY", "Reactivity"),
                        ("FOOD_GUARDING", "Food guarding"),
                        ("MEDICAL_ISSUES", "Medical issues"),
                        ("GERIATRIC", "Geriatric concerns"),
                        ("NONE_OF_ABOVE", "None of the above"),
                    ],
                    max_length=32,
                ),
                blank=True,
                default=None,
                null=True,
                size=None,
                verbose_name="Do you have experience with any of the following? Check all that apply.",
            ),
        ),
    ]
