# Generated by Django 4.1 on 2023-07-24 17:25

import caim_base.models.fosterer
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("caim_base", "0035_alter_fostererprofile_experience_categories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fostererprofile",
            name="existing_pets_details",
        ),
        migrations.RemoveField(
            model_name="fostererprofile",
            name="reference_1",
        ),
        migrations.RemoveField(
            model_name="fostererprofile",
            name="reference_2",
        ),
        migrations.RemoveField(
            model_name="fostererprofile",
            name="reference_3",
        ),
        migrations.RemoveField(
            model_name="fostererprofile",
            name="rent_ok_foster_pets",
        ),
        migrations.RemoveField(
            model_name="fostererprofile",
            name="timeframe_other",
        ),
        migrations.AddField(
            model_name="fostererprofile",
            name="age",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="fostererprofile",
            name="agree_social_media",
            field=models.CharField(
                choices=[("YES", "Yes"), ("NO", "No")],
                default=None,
                max_length=32,
                null=True,
                verbose_name="Do you agree to help promote your foster animal on social media and/or by attending adoption events and public outings?",
            ),
        ),
        migrations.AddField(
            model_name="fostererprofile",
            name="all_in_agreement",
            field=models.CharField(
                choices=[("YES", "Yes"), ("NO", "No")],
                default=None,
                max_length=32,
                null=True,
                verbose_name="Are all members of your household in agreement about fostering?",
            ),
        ),
        migrations.AddField(
            model_name="fostererprofile",
            name="behavioral_issues",
            field=models.CharField(
                choices=[
                    ("YES", "Yes"),
                    (
                        "MINOR",
                        "Not severe behavioral issues, but open to minor behavioral challenges.",
                    ),
                    ("NO", "No"),
                ],
                default=None,
                max_length=32,
                null=True,
                verbose_name="Would you be willing to foster an animal with behavioral issues?",
            ),
        ),
        migrations.AddField(
            model_name="fostererprofile",
            name="dog_size",
            field=caim_base.models.fosterer.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("SMALL", "Small (5 – 20 lbs)"),
                        ("MEDIUM", "Medium (21 – 50 lbs)"),
                        ("LARGE", "Large (50+ lbs)"),
                    ],
                    max_length=32,
                ),
                blank=True,
                default=None,
                null=True,
                size=None,
                verbose_name="Please check any / all that you're interested in fostering.",
            ),
        ),
        migrations.AddField(
            model_name="fostererprofile",
            name="medical_issues",
            field=models.CharField(
                choices=[("YES", "Yes"), ("NO", "No")],
                default=None,
                max_length=32,
                null=True,
                verbose_name="Would you be willing to foster an animal with medical issues?",
            ),
        ),
        migrations.AddField(
            model_name="fostererprofile",
            name="pet_allergies",
            field=models.CharField(
                choices=[("YES", "Yes"), ("NO", "No")],
                default=None,
                max_length=32,
                null=True,
                verbose_name="Does anyone in your home have pet allergies?",
            ),
        ),
        migrations.AddField(
            model_name="fostererprofile",
            name="special_needs",
            field=models.CharField(
                choices=[("YES", "Yes"), ("NO", "No")],
                default=None,
                max_length=32,
                null=True,
                verbose_name="Would you be willing to foster an animal with special needs?",
            ),
        ),
        migrations.AddField(
            model_name="fostererprofile",
            name="stairs",
            field=models.CharField(
                choices=[("YES", "Yes"), ("NO", "No")],
                default=None,
                max_length=32,
                null=True,
                verbose_name="Do you have stairs that a dog would have to walk daily?",
            ),
        ),
        migrations.AlterField(
            model_name="fostererprofile",
            name="agree_share_details",
            field=models.CharField(
                choices=[("YES", "Yes"), ("NO", "No")],
                default=None,
                max_length=32,
                null=True,
                verbose_name="Do you agree that we can share the details you've provided with rescues?",
            ),
        ),
        migrations.AlterField(
            model_name="fostererprofile",
            name="behavioural_attributes",
            field=caim_base.models.fosterer.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("GOOD_WITH_DOGS", "Good with dogs"),
                        ("GOOD_WITH_CATS", "Good with cats"),
                        ("GOOD_WITH_KIDS", "Good with children"),
                    ],
                    max_length=32,
                ),
                blank=True,
                default=None,
                null=True,
                size=None,
                verbose_name="Please check any of the requirements you have for a foster",
            ),
        ),
        migrations.AlterField(
            model_name="fostererprofile",
            name="category_of_animals",
            field=caim_base.models.fosterer.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("ADULT_FEMALE", "Adult female"),
                        ("ADULT_MALE", "Adult male"),
                        ("PREGNANT_MOTHER", "Pregnant mom"),
                        ("MOTHER_WITH_BABIES", "Mom with nursing babies"),
                        ("BABIES", "Puppies / kittens"),
                        ("PIT_BULLY_BREEDS", "Pit and/or Bully breeds"),
                        (
                            "SHEPARD_OR_MALINOIS",
                            "German Shepherd and/or Malinois breeds",
                        ),
                    ],
                    max_length=32,
                ),
                blank=True,
                default=None,
                null=True,
                size=None,
                verbose_name="Please check any / all that you're interested in fostering.",
            ),
        ),
        migrations.AlterField(
            model_name="fostererprofile",
            name="hours_alone_location",
            field=models.TextField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Where will your foster animal be kept when you're not home?",
            ),
        ),
        migrations.AlterField(
            model_name="fostererprofile",
            name="people_at_home",
            field=models.IntegerField(
                default=1,
                verbose_name="How many people live in your home, including yourself?",
            ),
        ),
        migrations.AlterField(
            model_name="fostererprofile",
            name="timeframe",
            field=models.CharField(
                choices=[
                    ("MAX_2_WEEKS", "Up to 2 weeks"),
                    ("MAX_3_MONTHS", "Up to 3 months"),
                    ("ANY_DURATION", "Any duration"),
                ],
                default=None,
                max_length=32,
                null=True,
                verbose_name="Please let us know which timeframe you're available for fostering",
            ),
        ),
        migrations.CreateModel(
            name="ReferenceDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=64)),
                ("last_name", models.CharField(max_length=64)),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, default=None, max_length=128, null=True, region=None
                    ),
                ),
                ("relation", models.CharField(max_length=128)),
                (
                    "fosterer_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="references",
                        to="caim_base.fostererprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PersonInHomeDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "relation",
                    models.CharField(
                        blank=True, default=None, max_length=128, null=True
                    ),
                ),
                ("age", models.IntegerField()),
                (
                    "email",
                    models.EmailField(
                        blank=True, default=None, max_length=254, null=True
                    ),
                ),
                (
                    "fosterer_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="people_in_home",
                        to="caim_base.fostererprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LandlordContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=64)),
                ("last_name", models.CharField(max_length=128)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, default=None, max_length=128, null=True, region=None
                    ),
                ),
                (
                    "fosterer_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="landlord_contact",
                        to="caim_base.fostererprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExistingPetDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, default=None, max_length=64, null=True
                    ),
                ),
                (
                    "type_of_animals",
                    caim_base.models.fosterer.ChoiceArrayField(
                        base_field=models.CharField(
                            choices=[("DOGS", "Dogs"), ("CATS", "Cats")], max_length=32
                        ),
                        blank=True,
                        default=None,
                        null=True,
                        size=None,
                        verbose_name="Animal Type",
                    ),
                ),
                (
                    "breed",
                    models.CharField(
                        blank=True, default=None, max_length=64, null=True
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=6
                    ),
                ),
                ("age", models.PositiveIntegerField()),
                ("weight_lbs", models.PositiveIntegerField()),
                (
                    "spayed_neutered",
                    models.CharField(
                        choices=[("YES", "Yes"), ("NO", "No")],
                        default=None,
                        max_length=32,
                        null=True,
                        verbose_name="Spayed or Neutered?",
                    ),
                ),
                (
                    "up_to_date_shots",
                    models.CharField(
                        choices=[("YES", "Yes"), ("NO", "No")],
                        default=None,
                        max_length=32,
                        null=True,
                        verbose_name="Up to date on their shots?",
                    ),
                ),
                (
                    "quirks",
                    models.TextField(
                        blank=True,
                        default=None,
                        max_length=1024,
                        null=True,
                        verbose_name="Any quirks?",
                    ),
                ),
                (
                    "fosterer_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="existing_pets",
                        to="caim_base.fostererprofile",
                    ),
                ),
            ],
        ),
    ]
