# Generated by Django 4.1 on 2023-07-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caim_base", "0035_alter_fostererprofile_experience_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="awg",
            name="awg_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SHELTER_ONLY", "Shelter only"),
                    ("FOSTER_ONLY", "Foster only"),
                    ("SHELTER_AND_FOSTER", "Both Shelter and Foster"),
                ],
                default=None,
                max_length=32,
                null=True,
                verbose_name="Organization type",
            ),
        ),
    ]
