# Generated by Django 4.1 on 2023-08-02 05:49

import caim_base.models.fosterer
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("caim_base", "0037_remove_fostererprofile_existing_pets_details_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FostererExistingPetDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "type_of_animals",
                    caim_base.models.fosterer.ChoiceArrayField(
                        base_field=models.CharField(
                            blank=True,
                            choices=[("DOGS", "Dogs"), ("CATS", "Cats")],
                            max_length=32,
                            null=True,
                        ),
                        size=None,
                        verbose_name="Animal Type",
                    ),
                ),
                ("breed", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "sex",
                    models.CharField(
                        blank=True,
                        choices=[("Male", "Male"), ("Female", "Female")],
                        max_length=6,
                        null=True,
                    ),
                ),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                ("weight_lbs", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "spayed_neutered",
                    models.CharField(
                        blank=True,
                        choices=[("YES", "Yes"), ("NO", "No")],
                        max_length=32,
                        null=True,
                        verbose_name="Spayed or Neutered?",
                    ),
                ),
                (
                    "up_to_date_shots",
                    models.CharField(
                        blank=True,
                        choices=[("YES", "Yes"), ("NO", "No")],
                        max_length=32,
                        null=True,
                        verbose_name="Up to date on their shots?",
                    ),
                ),
                (
                    "quirks",
                    models.TextField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        verbose_name="Any quirks?",
                    ),
                ),
                (
                    "fosterer_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="existing_pets",
                        to="caim_base.fostererprofile",
                    ),
                ),
            ],
        ),
        migrations.RenameModel(
            old_name="LandlordContact",
            new_name="FostererLandlordContact",
        ),
        migrations.RenameModel(
            old_name="PersonInHomeDetail",
            new_name="FostererPersonInHomeDetail",
        ),
        migrations.RenameModel(
            old_name="ReferenceDetail",
            new_name="FostererReferenceDetail",
        ),
        migrations.DeleteModel(
            name="ExistingPetDetail",
        ),
    ]
