# Generated by Django 4.1 on 2023-08-02 06:44

import caim_base.models.fosterer
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caim_base", "0038_fostererexistingpetdetail_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fostererexistingpetdetail",
            name="type_of_animals",
            field=caim_base.models.fosterer.ChoiceArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[("DOGS", "Dogs"), ("CATS", "Cats")],
                    max_length=32,
                    null=True,
                ),
                null=True,
                size=None,
                verbose_name="Animal Type",
            ),
        ),
    ]
