# Generated by Django 4.1 on 2023-08-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("caim_base", "0040_fostererprofile_num_people_in_home_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fostererprofile",
            name="landlord_contact_text",
            field=models.TextField(
                blank=True,
                default=None,
                null=True,
                verbose_name="If you rent, please provide your landlord’s name and contact information (email and/or phone). We will contact them to confirm that you have approval to foster.",
            ),
        ),
    ]
