# Generated by Django 4.1 on 2023-08-02 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("caim_base", "0037_fosterapplication_reject_reason_detail_and_more"),
        ("caim_base", "0041_fostererprofile_landlord_contact_text"),
    ]

    operations = []
