# Generated by Django 4.1 on 2023-08-04 04:53

import caim_base.models.fosterer
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("caim_base", "0043_alter_fosterapplication_reject_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fostererexistingpetdetail",
            name="type_of_animals",
            field=caim_base.models.fosterer.ChoiceArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[("DOG", "Dog"), ("CAT", "Cat")],
                    max_length=32,
                    null=True,
                ),
                null=True,
                size=None,
                verbose_name="Animal Type",
            ),
        ),
        migrations.AlterField(
            model_name="fostererprofile",
            name="behavioural_attributes",
            field=caim_base.models.fosterer.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("GOOD_WITH_DOGS", "Good with dogs"),
                        ("GOOD_WITH_CATS", "Good with cats"),
                        ("GOOD_WITH_KIDS", "Good with children"),
                    ],
                    max_length=32,
                ),
                blank=True,
                default=None,
                null=True,
                size=None,
                verbose_name="Please check any of the requirements you have for a foster animal.",
            ),
        ),
        migrations.AlterField(
            model_name="fostererprofile",
            name="experience_categories",
            field=caim_base.models.fosterer.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("HOUSE_POTTY", "House / potty training"),
                        ("CRATE", "Crate training"),
                        ("LEASH_WALKING", "Challenges with leash / walking"),
                        ("JUMPING", "Jumping"),
                        ("HIGH_ENERGY", "High energy"),
                        ("OBEDIENCE", "Basic obedience"),
                        ("PUPPIES", "Training puppies"),
                        ("SEPARATION_ANXIETY", "Separation anxiety"),
                        ("FEARS", "Fears / phobias"),
                        ("REACTIVITY", "Reactivity"),
                        ("FOOD_GUARDING", "Food guarding"),
                        ("MEDICAL_ISSUES", "Medical issues"),
                        ("GERIATRIC", "Geriatric concerns"),
                        ("NONE_OF_ABOVE", "None of the above"),
                    ],
                    max_length=32,
                ),
                blank=True,
                default=None,
                null=True,
                size=None,
                verbose_name="Have you had experience with any of the following in animals you’ve owned or fostered?",
            ),
        ),
        migrations.AlterField(
            model_name="fostererprofile",
            name="timeframe",
            field=models.CharField(
                choices=[
                    ("MAX_2_WEEKS", "Up to 2 weeks"),
                    ("MAX_3_MONTHS", "Up to 3 months"),
                    ("ANY_DURATION", "Any duration"),
                ],
                default=None,
                max_length=32,
                null=True,
                verbose_name="How long are you able to foster an animal for?",
            ),
        ),
        migrations.AlterField(
            model_name="fostererreferencedetail",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default=None, max_length=128, null=True, region=None
            ),
        ),
    ]
