# Generated by Django 4.1 on 2023-08-07 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("caim_base", "0045_awgmember_canviewapplications_and_more"),
        ("caim_base", "0045_remove_fostererexistingpetdetail_type_of_animals_and_more"),
    ]

    operations = []
