# Generated by Django 4.1 on 2023-08-29 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("caim_base", "0046_merge_20230807_1826"),
    ]

    operations = [
        migrations.CreateModel(
            name="FosterApplicationAnimalSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submitted_on", models.DateField(auto_now_add=True)),
                ("updated_on", models.DateField(auto_now=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alternative_suggested_animals",
                        to="caim_base.fosterapplication",
                    ),
                ),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="caim_base.animal",
                    ),
                ),
            ],
        ),
    ]
