# Generated by Django 4.1 on 2023-08-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("caim_base", "0046_merge_20230807_1826"),
    ]

    operations = [
        migrations.AlterField(
            model_name="awg",
            name="email",
            field=models.EmailField(
                blank=True, default=None, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="fostererlandlordcontact",
            name="email",
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="fostererpersoninhomedetail",
            name="email",
            field=models.EmailField(
                blank=True, default=None, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="fostererreferencedetail",
            name="email",
            field=models.EmailField(max_length=255),
        ),
    ]
