# Generated by Django 4.1 on 2023-08-31 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("caim_base", "0047_alter_emails_to_255_max_length"),
        ("caim_base", "0047_fosterapplicationanimalsuggestion"),
    ]

    operations = []
