# Generated by Django 4.1 on 2023-09-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caim_base", "0048_merge_20230905_0325"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fostererprofile",
            name="num_people_in_home",
            field=models.IntegerField(
                blank=True,
                default=None,
                null=True,
                verbose_name="How many people live in your home, excluding yourself?",
            ),
        ),
    ]
