# Generated by Django 4.1 on 2023-10-03 14:45

import caim_base.models.fosterer
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("caim_base", "0048_merge_20230905_0325"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fosterapplication",
            name="reject_reason",
            field=models.CharField(
                choices=[
                    (
                        "UNSUITABLE",
                        "Not suitable for the animal requested, and not willing to consider alternative",
                    ),
                    ("UNRELIABLE", "Concerns about fosterer reliability/commitment"),
                    ("PROPERTY", "Concerns with home and/or yard situation"),
                    ("HUMAN_ROOMMATES", "Concerns with the people in the home"),
                    ("PET_ROOMMATES", "Concerns with the other pets in the home"),
                    ("NO_LANDLORD_APPROVAL", "Landlord has not approved fostering"),
                    ("LIED", "Lied on Application"),
                    ("OTHER", "Other"),
                ],
                default="default reject_reason",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="fostererexistingpetdetail",
            name="age",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="fostererexistingpetdetail",
            name="breed",
            field=models.CharField(default="N/A", max_length=64),
        ),
        migrations.AlterField(
            model_name="fostererexistingpetdetail",
            name="name",
            field=models.CharField(default="N/A", max_length=64),
        ),
        migrations.AlterField(
            model_name="fostererexistingpetdetail",
            name="sex",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")],
                default="N/A",
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="fostererexistingpetdetail",
            name="spayed_neutered",
            field=models.CharField(
                choices=[("YES", "Yes"), ("NO", "No")],
                default="N/A",
                max_length=32,
                verbose_name="Spayed or Neutered?",
            ),
        ),
        migrations.AlterField(
            model_name="fostererexistingpetdetail",
            name="type_of_animal",
            field=models.CharField(default="N/A", max_length=64),
        ),
        migrations.AlterField(
            model_name="fostererexistingpetdetail",
            name="up_to_date_shots",
            field=models.CharField(
                choices=[("YES", "Yes"), ("NO", "No")],
                default="N/A",
                max_length=32,
                verbose_name="Up to date on their shots?",
            ),
        ),
        migrations.AlterField(
            model_name="fostererexistingpetdetail",
            name="weight_lbs",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="fostererlandlordcontact",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default=None, max_length=128, region=None
            ),
        ),
        migrations.AlterField(
            model_name="fostererpersoninhomedetail",
            name="age",
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name="fostererpersoninhomedetail",
            name="email",
            field=models.EmailField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name="fostererpersoninhomedetail",
            name="name",
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name="fostererpersoninhomedetail",
            name="relation",
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name="fostererprofile",
            name="age",
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name="fostererprofile",
            name="agree_share_details",
            field=models.CharField(
                choices=[("YES", "Yes"), ("NO", "No")],
                default=None,
                max_length=32,
                verbose_name="Do you agree that we can share the details you've provided with rescues?",
            ),
        ),
        migrations.AlterField(
            model_name="fostererprofile",
            name="agree_social_media",
            field=models.CharField(
                choices=[("YES", "Yes"), ("NO", "No")],
                default=None,
                max_length=32,
                verbose_name="Do you agree to help promote your foster animal on social media and/or by attending adoption events and public outings?",
            ),
        ),
        migrations.AlterField(
            model_name="fostererprofile",
            name="all_in_agreement",
            field=models.CharField(
                choices=[("YES", "Yes"), ("NO", "No")],
                default=None,
                max_length=32,
                verbose_name="Are all members of your household in agreement about fostering?",
            ),
        ),
        migrations.AlterField(
            model_name="fostererprofile",
            name="behavioural_attributes",
            field=caim_base.models.fosterer.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("GOOD_WITH_DOGS", "Good with dogs"),
                        ("GOOD_WITH_CATS", "Good with cats"),
                        ("GOOD_WITH_KIDS", "Good with children"),
                    ],
                    max_length=32,
                ),
                default=None,
                size=None,
                verbose_name="Please check any of the requirements you have for a foster animal.",
            ),
        ),
        migrations.AlterField(
            model_name="fostererprofile",
            name="category_of_animals",
            field=caim_base.models.fosterer.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("ADULT_FEMALE", "Adult female"),
                        ("ADULT_MALE", "Adult male"),
                        ("PREGNANT_MOTHER", "Pregnant mom"),
                        ("MOTHER_WITH_BABIES", "Mom with nursing babies"),
                        ("BABIES", "Puppies / kittens"),
                        ("PIT_BULLY_BREEDS", "Pit and/or Bully breeds"),
                        (
                            "SHEPARD_OR_MALINOIS",
                            "German Shepherd and/or Malinois breeds",
                        ),
                    ],
                    max_length=32,
                ),
                default=None,
                size=None,
                verbose_name="Please check any / all that you're interested in fostering.",
            ),
        ),
        migrations.AlterField(
            model_name="fostererprofile",
            name="city",
            field=models.CharField(default=None, max_length=32),
        ),
        migrations.AlterField(
            model_name="fostererprofile",
            name="email",
            field=models.EmailField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name="fostererprofile",
            name="ever_been_convicted_abuse",
            field=models.CharField(
                choices=[("YES", "Yes"), ("NO", "No")],
                default=None,
                max_length=32,
                verbose_name="Have you or a family / household member ever been convicted of an animal related crime (animal abuse, neglect, abandonment, etc.)?",
            ),
        ),
        migrations.AlterField(
            model_name="fostererprofile",
            name="firstname",
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AlterField(
            model_name="fostererprofile",
            name="hours_alone_description",
            field=models.TextField(
                blank=True,
                default=None,
                verbose_name="How many hours per day will your foster animal be left alone?",
            ),
        ),
        migrations.AlterField(
            model_name="fostererprofile",
            name="hours_alone_location",
            field=models.TextField(
                blank=True,
                default=None,
                verbose_name="Where will your foster animal be kept when you're not home?",
            ),
        ),
        migrations.AlterField(
            model_name="fostererprofile",
            name="lastname",
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AlterField(
            model_name="fostererprofile",
            name="num_people_in_home",
            field=models.IntegerField(
                blank=True,
                default=None,
                verbose_name="How many people live in your home, excluding yourself?",
            ),
        ),
        migrations.AlterField(
            model_name="fostererprofile",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default=None, max_length=128, region=None
            ),
        ),
        migrations.AlterField(
            model_name="fostererprofile",
            name="rent_own",
            field=models.CharField(
                choices=[("RENT", "Rent"), ("OWN", "Own")],
                default=None,
                max_length=32,
                verbose_name="Do you rent or own?",
            ),
        ),
        migrations.AlterField(
            model_name="fostererprofile",
            name="sleep_location",
            field=models.TextField(
                blank=True,
                default=None,
                verbose_name="Where will your foster animal sleep?",
            ),
        ),
        migrations.AlterField(
            model_name="fostererprofile",
            name="state",
            field=models.CharField(
                choices=[
                    ("AK", "Alaska"),
                    ("AL", "Alabama"),
                    ("AR", "Arkansas"),
                    ("AZ", "Arizona"),
                    ("CA", "California"),
                    ("CO", "Colorado"),
                    ("CT", "Connecticut"),
                    ("DC", "District of Columbia"),
                    ("DE", "Delaware"),
                    ("FL", "Florida"),
                    ("GA", "Georgia"),
                    ("HI", "Hawaii"),
                    ("IA", "Iowa"),
                    ("ID", "Idaho"),
                    ("IL", "Illinois"),
                    ("IN", "Indiana"),
                    ("KS", "Kansas"),
                    ("KY", "Kentucky"),
                    ("LA", "Louisiana"),
                    ("MA", "Massachusetts"),
                    ("MD", "Maryland"),
                    ("ME", "Maine"),
                    ("MI", "Michigan"),
                    ("MN", "Minnesota"),
                    ("MO", "Missouri"),
                    ("MS", "Mississippi"),
                    ("MT", "Montana"),
                    ("NC", "North Carolina"),
                    ("ND", "North Dakota"),
                    ("NE", "Nebraska"),
                    ("NH", "New Hampshire"),
                    ("NJ", "New Jersey"),
                    ("NM", "New Mexico"),
                    ("NV", "Nevada"),
                    ("NY", "New York"),
                    ("OH", "Ohio"),
                    ("OK", "Oklahoma"),
                    ("OR", "Oregon"),
                    ("PA", "Pennsylvania"),
                    ("RI", "Rhode Island"),
                    ("SC", "South Carolina"),
                    ("SD", "South Dakota"),
                    ("TN", "Tennessee"),
                    ("TX", "Texas"),
                    ("UT", "Utah"),
                    ("VA", "Virginia"),
                    ("VT", "Vermont"),
                    ("WA", "Washington"),
                    ("WI", "Wisconsin"),
                    ("WV", "West Virginia"),
                    ("WY", "Wyoming"),
                ],
                default=None,
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="fostererprofile",
            name="street_address",
            field=models.CharField(default=None, max_length=244),
        ),
        migrations.AlterField(
            model_name="fostererprofile",
            name="type_of_animals",
            field=caim_base.models.fosterer.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[("DOGS", "Dogs"), ("CATS", "Cats")], max_length=32
                ),
                default=None,
                size=None,
                verbose_name="Which type of animal(s) are you wanting to foster?",
            ),
        ),
        migrations.AlterField(
            model_name="fostererprofile",
            name="zip_code",
            field=models.CharField(default=None, max_length=16),
        ),
    ]
