# Generated by Django 4.1 on 2023-09-16 22:36

from django.db import migrations, models
from caim_base.migrations.utils.set_values_for_non_nulls import (
    set_values_for_non_nulls,
    reverse_set_values_for_non_nulls
)


class Migration(migrations.Migration):

    dependencies = [
        ("caim_base", "0048_merge_20230905_0325"),
    ]

    operations = [
        migrations.RunPython(set_values_for_non_nulls, reverse_set_values_for_non_nulls),
        migrations.AlterField(
            model_name="fosterapplication",
            name="reject_reason",
            field=models.CharField(
                choices=[
                    (
                        "UNSUITABLE",
                        "Not suitable for the animal requested, and not willing to consider alternative",
                    ),
                    ("UNRELIABLE", "Concerns about fosterer reliability/commitment"),
                    ("PROPERTY", "Concerns with home and/or yard situation"),
                    ("HUMAN_ROOMMATES", "Concerns with the people in the home"),
                    ("PET_ROOMMATES", "Concerns with the other pets in the home"),
                    ("NO_LANDLORD_APPROVAL", "Landlord has not approved fostering"),
                    ("LIED", "Lied on Application"),
                    ("OTHER", "Other"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="fostererprofile",
            name="age",
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name="fostererprofile",
            name="num_people_in_home",
            field=models.IntegerField(
                blank=True,
                default=None,
                verbose_name="How many people live in your home, excluding yourself?",
            ),
        ),
        migrations.AlterField(
            model_name="fostererprofile",
            name="reference_1",
            field=models.TextField(default=None, verbose_name="Reference #1"),
        ),
        migrations.AlterField(
            model_name="fostererprofile",
            name="reference_2",
            field=models.TextField(default=None, verbose_name="Reference #2"),
        ),
        migrations.AlterField(
            model_name="fostererprofile",
            name="reference_3",
            field=models.TextField(default=None, verbose_name="Reference #3"),
        ),
    ]
