# Generated by Django 4.1 on 2023-09-18 18:49

import caim_base.models.fosterer
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("caim_base", "0049_alter_fostererprofile_num_people_in_home"),
    ]

    operations = [
        migrations.CreateModel(
            name="FostererApplicationProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "firstname",
                    models.CharField(
                        blank=True, default=None, max_length=64, null=True
                    ),
                ),
                (
                    "lastname",
                    models.CharField(
                        blank=True, default=None, max_length=64, null=True
                    ),
                ),
                ("age", models.IntegerField(blank=True, default=None, null=True)),
                (
                    "email",
                    models.EmailField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, default=None, max_length=128, null=True, region=None
                    ),
                ),
                (
                    "street_address",
                    models.CharField(
                        blank=True, default=None, max_length=244, null=True
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, default=None, max_length=32, null=True
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AK", "Alaska"),
                            ("AL", "Alabama"),
                            ("AR", "Arkansas"),
                            ("AZ", "Arizona"),
                            ("CA", "California"),
                            ("CO", "Colorado"),
                            ("CT", "Connecticut"),
                            ("DC", "District of Columbia"),
                            ("DE", "Delaware"),
                            ("FL", "Florida"),
                            ("GA", "Georgia"),
                            ("HI", "Hawaii"),
                            ("IA", "Iowa"),
                            ("ID", "Idaho"),
                            ("IL", "Illinois"),
                            ("IN", "Indiana"),
                            ("KS", "Kansas"),
                            ("KY", "Kentucky"),
                            ("LA", "Louisiana"),
                            ("MA", "Massachusetts"),
                            ("MD", "Maryland"),
                            ("ME", "Maine"),
                            ("MI", "Michigan"),
                            ("MN", "Minnesota"),
                            ("MO", "Missouri"),
                            ("MS", "Mississippi"),
                            ("MT", "Montana"),
                            ("NC", "North Carolina"),
                            ("ND", "North Dakota"),
                            ("NE", "Nebraska"),
                            ("NH", "New Hampshire"),
                            ("NJ", "New Jersey"),
                            ("NM", "New Mexico"),
                            ("NV", "Nevada"),
                            ("NY", "New York"),
                            ("OH", "Ohio"),
                            ("OK", "Oklahoma"),
                            ("OR", "Oregon"),
                            ("PA", "Pennsylvania"),
                            ("RI", "Rhode Island"),
                            ("SC", "South Carolina"),
                            ("SD", "South Dakota"),
                            ("TN", "Tennessee"),
                            ("TX", "Texas"),
                            ("UT", "Utah"),
                            ("VA", "Virginia"),
                            ("VT", "Vermont"),
                            ("WA", "Washington"),
                            ("WI", "Wisconsin"),
                            ("WV", "West Virginia"),
                            ("WY", "Wyoming"),
                        ],
                        default=None,
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "zip_code",
                    models.CharField(
                        blank=True, default=None, max_length=16, null=True
                    ),
                ),
                (
                    "type_of_animals",
                    caim_base.models.fosterer.ChoiceArrayField(
                        base_field=models.CharField(
                            choices=[("DOGS", "Dogs"), ("CATS", "Cats")], max_length=32
                        ),
                        blank=True,
                        default=None,
                        null=True,
                        size=None,
                        verbose_name="Which type of animal(s) are you wanting to foster?",
                    ),
                ),
                (
                    "category_of_animals",
                    caim_base.models.fosterer.ChoiceArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("ADULT_FEMALE", "Adult female"),
                                ("ADULT_MALE", "Adult male"),
                                ("PREGNANT_MOTHER", "Pregnant mom"),
                                ("MOTHER_WITH_BABIES", "Mom with nursing babies"),
                                ("BABIES", "Puppies / kittens"),
                                ("PIT_BULLY_BREEDS", "Pit and/or Bully breeds"),
                                (
                                    "SHEPARD_OR_MALINOIS",
                                    "German Shepherd and/or Malinois breeds",
                                ),
                            ],
                            max_length=32,
                        ),
                        blank=True,
                        default=None,
                        null=True,
                        size=None,
                        verbose_name="Please check any / all that you're interested in fostering.",
                    ),
                ),
                (
                    "dog_size",
                    caim_base.models.fosterer.ChoiceArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("SMALL", "Small (5 – 20 lbs)"),
                                ("MEDIUM", "Medium (21 – 50 lbs)"),
                                ("LARGE", "Large (50+ lbs)"),
                            ],
                            max_length=32,
                        ),
                        blank=True,
                        default=None,
                        null=True,
                        size=None,
                        verbose_name="If you’re interested in fostering dogs, do you have a preference about size?",
                    ),
                ),
                (
                    "behavioural_attributes",
                    caim_base.models.fosterer.ChoiceArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("GOOD_WITH_DOGS", "Good with dogs"),
                                ("GOOD_WITH_CATS", "Good with cats"),
                                ("GOOD_WITH_KIDS", "Good with children"),
                            ],
                            max_length=32,
                        ),
                        blank=True,
                        default=None,
                        null=True,
                        size=None,
                        verbose_name="Please check any of the requirements you have for a foster animal.",
                    ),
                ),
                (
                    "medical_issues",
                    models.CharField(
                        choices=[("YES", "Yes"), ("NO", "No")],
                        default=None,
                        max_length=32,
                        null=True,
                        verbose_name="Would you be willing to foster an animal with medical issues?",
                    ),
                ),
                (
                    "special_needs",
                    models.CharField(
                        choices=[("YES", "Yes"), ("NO", "No")],
                        default=None,
                        max_length=32,
                        null=True,
                        verbose_name="Would you be willing to foster an animal with special needs?",
                    ),
                ),
                (
                    "behavioral_issues",
                    models.CharField(
                        choices=[
                            ("YES", "Yes"),
                            (
                                "MINOR",
                                "Not severe behavioral issues, but open to minor behavioral challenges.",
                            ),
                            ("NO", "No"),
                        ],
                        default=None,
                        max_length=32,
                        null=True,
                        verbose_name="Would you be willing to foster an animal with behavioral issues?",
                    ),
                ),
                (
                    "timeframe",
                    models.CharField(
                        choices=[
                            ("MAX_2_WEEKS", "Up to 2 weeks"),
                            ("MAX_3_MONTHS", "Up to 3 months"),
                            ("ANY_DURATION", "Any duration"),
                        ],
                        default=None,
                        max_length=32,
                        null=True,
                        verbose_name="How long are you able to foster an animal for?",
                    ),
                ),
                (
                    "num_existing_pets",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="How many pets do you currently have in your home?",
                    ),
                ),
                (
                    "experience_given_up_pet",
                    models.TextField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Have you ever given a pet up? If so, please describe the situation.",
                    ),
                ),
                (
                    "experience_description",
                    models.TextField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Please describe your experience with animals (personal pets, training, interactions, etc.)",
                    ),
                ),
                (
                    "experience_categories",
                    caim_base.models.fosterer.ChoiceArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("HOUSE_POTTY", "House / potty training"),
                                ("CRATE", "Crate training"),
                                ("LEASH_WALKING", "Challenges with leash / walking"),
                                ("JUMPING", "Jumping"),
                                ("HIGH_ENERGY", "High energy"),
                                ("OBEDIENCE", "Basic obedience"),
                                ("PUPPIES", "Training puppies"),
                                ("SEPARATION_ANXIETY", "Separation anxiety"),
                                ("FEARS", "Fears / phobias"),
                                ("REACTIVITY", "Reactivity"),
                                ("FOOD_GUARDING", "Food guarding"),
                                ("MEDICAL_ISSUES", "Medical issues"),
                                ("GERIATRIC", "Geriatric concerns"),
                                ("NONE_OF_ABOVE", "None of the above"),
                            ],
                            max_length=32,
                        ),
                        blank=True,
                        default=None,
                        null=True,
                        size=None,
                        verbose_name="Have you had experience with any of the following in animals you’ve owned or fostered?",
                    ),
                ),
                (
                    "reference_1",
                    models.TextField(
                        blank=True, default=None, null=True, verbose_name="Reference #1"
                    ),
                ),
                (
                    "reference_2",
                    models.TextField(
                        blank=True, default=None, null=True, verbose_name="Reference #2"
                    ),
                ),
                (
                    "reference_3",
                    models.TextField(
                        blank=True, default=None, null=True, verbose_name="Reference #3"
                    ),
                ),
                (
                    "people_at_home",
                    models.TextField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Please list how many people live in your home and their ages (legacy)",
                    ),
                ),
                (
                    "num_people_in_home",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="How many people live in your home, excluding yourself?",
                    ),
                ),
                (
                    "people_in_home_detail",
                    models.TextField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Please list the following details for each person in your home, excluding yourself: Name, Relation, Age, Email address.",
                    ),
                ),
                (
                    "all_in_agreement",
                    models.CharField(
                        choices=[("YES", "Yes"), ("NO", "No")],
                        default=None,
                        max_length=32,
                        null=True,
                        verbose_name="Are all members of your household in agreement about fostering?",
                    ),
                ),
                (
                    "pet_allergies",
                    models.CharField(
                        choices=[("YES", "Yes"), ("NO", "No")],
                        default=None,
                        max_length=32,
                        null=True,
                        verbose_name="Does anyone in your home have pet allergies?",
                    ),
                ),
                (
                    "stairs",
                    models.CharField(
                        choices=[("YES", "Yes"), ("NO", "No")],
                        default=None,
                        max_length=32,
                        null=True,
                        verbose_name="Do you have stairs that a dog would have to walk daily?",
                    ),
                ),
                (
                    "yard_type",
                    models.CharField(
                        choices=[
                            ("NO_YARD", "No yard"),
                            ("UNFENCED", "Unfenced yard"),
                            ("PARTIALLY_FENCED", "Partially fenced yard"),
                            ("FULLY_FENCED", "Fully fenced yard"),
                        ],
                        default=None,
                        max_length=32,
                        null=True,
                        verbose_name="Describe your yard",
                    ),
                ),
                (
                    "yard_fence_over_5ft",
                    models.CharField(
                        choices=[("YES", "Yes"), ("NO", "No")],
                        default=None,
                        max_length=32,
                        null=True,
                        verbose_name="If your yard is fully fenced, is it all over 5 feet tall?",
                    ),
                ),
                (
                    "rent_own",
                    models.CharField(
                        choices=[("RENT", "Rent"), ("OWN", "Own")],
                        default=None,
                        max_length=32,
                        null=True,
                        verbose_name="Do you rent or own?",
                    ),
                ),
                (
                    "rent_restrictions",
                    models.TextField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="If you rent, please describe any pet restrictions that are in place.",
                    ),
                ),
                (
                    "landlord_contact_text",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=128,
                        null=True,
                        verbose_name="If you rent, please provide your landlord’s contact information (email and/or phone). We will contact them to confirm that you have approval to foster.",
                    ),
                ),
                (
                    "hours_alone_description",
                    models.TextField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="How many hours per day will your foster animal be left alone?",
                    ),
                ),
                (
                    "hours_alone_location",
                    models.TextField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Where will your foster animal be kept when you're not home?",
                    ),
                ),
                (
                    "sleep_location",
                    models.TextField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Where will your foster animal sleep?",
                    ),
                ),
                (
                    "other_info",
                    models.TextField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Is there anything else you want us / rescues to know?",
                    ),
                ),
                (
                    "ever_been_convicted_abuse",
                    models.CharField(
                        choices=[("YES", "Yes"), ("NO", "No")],
                        default=None,
                        max_length=32,
                        null=True,
                        verbose_name="Have you or a family / household member ever been convicted of an animal related crime (animal abuse, neglect, abandonment, etc.)?",
                    ),
                ),
                (
                    "agree_share_details",
                    models.CharField(
                        choices=[("YES", "Yes"), ("NO", "No")],
                        default=None,
                        max_length=32,
                        null=True,
                        verbose_name="Do you agree that we can share the details you've provided with rescues?",
                    ),
                ),
                (
                    "agree_social_media",
                    models.CharField(
                        choices=[("YES", "Yes"), ("NO", "No")],
                        default=None,
                        max_length=32,
                        null=True,
                        verbose_name="Do you agree to help promote your foster animal on social media and/or by attending adoption events and public outings?",
                    ),
                ),
                ("is_complete", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="fosterapplication",
            name="fosterer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="caim_base.fostererapplicationprofile",
            ),
        ),
    ]
